# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'


strategy:
  matrix:
    Python 3.9:
      python.version: '3.9'
  maxParallel: 1


variables:
  LT_USERNAME: 'neerajn'
  LT_ACCESS_KEY: '0z5UPFS7WDpZutTHEfSZWn3iOZz8Eydmh49evnJuNEqjTaXCd8'
  
steps:
- task: configuration@1
  inputs:
    connection: 'trstbasicauth'
    isTunnelActivate: true
    tunnelOptions: '{   "tunnelName": "Testbasicauth",   "basic-auth": "https://stg.aemsites:F93bwU8c9G@stg-www.mercuryracing.com",   "mitm": true,   "logFile": "D:\\a\\1\\a\\logs",   "v": true }'
    isAppAutomate: false
    isSmartUI: false

- task: CmdLine@2
  inputs:
    script: 'sleep 360'

# - task: UsePythonVersion@0
#   inputs: 
#     versionSpec: '$(python.version)'
#     architecture: 'x64'

# - script: pip install robotframework robotframework-seleniumlibrary webdrivermanager
#   displayName: 'Install dependencies'

# - script: make run_all_in_parallel
#   displayName: 'Run Robot Framework Tests' 
#   continueOnError: true

- task: stoptunnel@1
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


# - task: PublishTestResults@2
#   displayName: 'Publish Test Results'
#   continueOnError: true
#   inputs:
#     testResultsFiles: outputxunit.xml
#     publishRunAttachments: true

# - task: CopyFiles@2
#   inputs:
#     contents: '_buildOutput/**'
#     targetFolder: $(Build.SourcesDirectory)





